[package]
name = "day4"
version = "0.1.0"
authors = ["Sean Perry <shalehperry@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
advent-support = {path = "../advent_support"}
md-5 = "0.9.1"